models:
  core: qwen2.5:7b
  embed: nomic-embed-text
  url: ollama
  port: 11434

csv:
  directory: csvs
  max:
    files: 5
    size: 10000

cleanup:
  interval_seconds: 900

redis:
  host: redis
  port: 6379
  db: 0
  expire_seconds: 3600